version: 2.1

orbs:
    python: circleci/python@2.1.1
    heroku: circleci/heroku@2.0.0
    
jobs:
    build:
        executor: python/default
        steps:
            - checkout
            - python/install-packages:
                  pkg-manager: pip
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - .
    test:
        executor:
            - attach_workspace:
                  at: ~/project
        steps:
            - run:
                  name: Run tests
                  command: python -m pytest

workflows:
    build_test:
        jobs:
            - build
            - test:
                  requires:
                      - build

