version: 2.1

orbs:
    python: circleci/python@2.1.1
    heroku: circleci/heroku@2.0.0
    browser-tools: circleci/browser-tools@1.4.4
    
parameters:
    chrome-version:
        default: 116.0.5845.96
jobs:
    build_and_test:
        executor: python/default
        steps:
            - checkout
            - python/install-packages:
                  pkg-manager: pip
            - browser-tools/install-chrome
            - browser-tools/install-chromedriver
            - run:
                command: |
                    google-chrome --version
                    chromedriver --version
                name: Check install
            - run:
                  name: Run tests
                  command: python -m pytest
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - .
    deploy:
        executor: heroku/default
        steps:
            - attach_workspace:
                  at: ~/project
            - heroku/deploy-via-git:
                  force: true

                
workflows:
    build_test_deploy:
        jobs:
            - build_and_test
            - deploy:
                  requires:
                      - build_and_test
                  filters:
                      branches:
                          only: main

